name:                inalys
version:             0.1.0.0
github:              "delirehberi/inalys"
license:             BSD3
author:              "Emre YILMAZ"
maintainer:          "z@emre.xyz"
copyright:           "2019 Emre"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/inalys#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- raw-strings-qq
- text
- network
- unordered-containers

library:
  source-dirs: src

executables:
  inalys-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - inalys

tests:
  inalys-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - inalys
